#!/bin/bash
#bdereims@vmware.com

#######################

# export CPOD=XXX
# export SUBNET=172.18.XX

#######################

CPOD_LOWER=$( echo ${CPOD} | tr '[:upper:]' '[:lower:]' )
export DOMAIN=cpod-${CPOD_LOWER}.shwrfr.mooo.com
export DNS=${SUBNET}.1
export NTP=${DNS}
export GATEWAY=${DNS}
export NETMASK=255.255.255.0
export PASSWORD=VMware1!
export VC_PASSWORD=${PASSWORD}
export PORTGROUP="VM Network"
export ADMIN=administrator%40vsphere.local
export TARGET=vcsa.${DOMAIN}/cPod-${CPOD}/host/Cluster
export DATASTORE=Datastore
export BITS=/data/BITS

export HOSTNAME_VCSA=vcsa.${DOMAIN}
export NAME_VCSA=VCSA
export IP_VCSA=${SUBNET}.20
export OVA_VCSA=${BITS}/VMware-VCSA-all-6.5.0-5973321.iso
export TARGET_VCSA=${SUBNET}.11
export DATASTORE_VCSA=Datastore
export PORTGROUP_VCSA="VM Network"

export HOSTNAME_NSX=nsx.${DOMAIN}
export NAME_NSX=NSX
export IP_NSX=${SUBNET}.21
export OVA_NSX=${BITS}/VMware-NSX-Manager-6.3.3-6276725.ova

export HOSTNAME_PHOTONOS=photonos
export NAME_PHOTONOS=photonos
export OVA_PHOTONOS=${BITS}/photon-custom-hw10-1.0-62c543d.ova
