#!/bin/bash
#bdereims@vmware.com

export DNS=172.18.1.1
export NTP=${DNS}
export DOMAIN=cpod-vic.shwrfr.mooo.com
export GATEWAY=172.18.1.1
export NETMASK=255.255.255.0
export PASSWORD=VMware1!
export VC_PASSWORD=${PASSWORD}
export PORTGROUP="DPortGroup"
export ADMIN=administrator%40vsphere.local
export TARGET=vcsa.cpod-vic.shwrfr.mooo.com/cPod-VIC/host/Management/
export DATASTORE=Datastore
export BITS=../../BITS
