#!/bin/bash
#bdereims@vmware.com

export DNS=172.18.1.1
export NTP=${DNS}
export DOMAIN=cpod-vic.shwrfr.mooo.com
export GATEWAY=172.18.1.1
export NETMASK=255.255.255.0
export PASSWORD=VMware1!
export VC_PASSWORD=${PASSWORD}
export PORTGROUP="VM Network"
export ADMIN=administrator%40vsphere.local
export TARGET=esx-03.cpod-vic.shwrfr.mooo.com
export DATASTORE=Temp
export BITS=../../BITS
