#!/bin/bash
#bdereims@vmware.com

export DNS=10.66.0.15
export NTP=${DNS}
export DOMAIN=cpod.showroom.local
export GATEWAY=10.66.0.1
export NETMASK=255.255.255.0
export PASSWORD=VMware1!
export VC_PASSWORD=${PASSWORD}
export PORTGROUP="VM Network"
export ADMIN=administrator%40vsphere.local
export TARGET=vcsa.cpod.showroom.local/Datacenter/host/Cluster/esxcloud04.cpod.showroom.local/
export DATASTORE=datastoreRAID5
export BITS=../../BITS
export VIC_DIR=../../vic
