#!/bin/bash
#bdereims@vmware.com

export DNS=172.18.1.1
export NTP=${DNS}
export DOMAIN=cpod-vic.shwrfr.mooo.com
export GATEWAY=172.18.1.1
export NETMASK=255.255.255.0
export PASSWORD=VMware1!
export VC_PASSWORD=${PASSWORD}
export PORTGROUP="DPortGroup"
export BRIDGE="DPortGroup"
export ADMIN=administrator@vsphere.local
export VCSA=vcsa.${DOMAIN}
export TARGET=${VCSA}/cPod-VIC
export VCH=VCH01
export CLUSTER=Cluster
export DATASTORE=Datastore
export BITS=../../BITS
export VIC_DIR=../../../vic
