#!/bin/bash
#bdereims@vmware.com

export OVFDIR=/root/ovftool
export DNS=172.16.60.1
export NTP=${DNS}
export DOMAIN=cpod.net
export GATEWAY=172.16.66.1
export NETMASK=255.255.255.0
export PASSWORD=VMware1!
export PORTGROUP="VM Network"
export ADMIN=root
export DATASTORE=vsanDatastore
export BITS=/root/BITS
export TARGET=esx01.cpod.net

export PCIP=172.16.66.110
export PHOTONENV=photon-starships.yaml
