#!/bin/bash
#bdereims@vmware.com

export DNS=172.18.11.1
export NTP=${DNS}
export DOMAIN=cpod-tom-vio.shwrfr.mooo.com
export GATEWAY=172.18.11.1
export NETMASK=255.255.255.0
export PASSWORD=VMware1!
export VC_PASSWORD=${PASSWORD}
export PORTGROUP="DPortGroup"
export ADMIN=administrator%40vsphere.local
export TARGET=vcsa.cpod-vio.shwrfr.mooo.com/cPod-VIO/host/Management/
export DATASTORE=Datastore
export BITS=../../BITS

export HOSTNAME_VIO=oms
export NAME_VIO=oms
export IP_VIO=172.18.0.97
export OVA_VIO=${BITS}/VMware-OpenStack-3.1.0.0-5065461_OVF10.ova

export HOSTNAME_VCSA=vcsa.${DOMAIN}
export NAME_VCSA=VCSA
export IP_VCSA=172.18.11.30
export OVA_VCSA=${BITS}/VMware-VCSA-all-6.5.0-5318154.iso
export TARGET_VCSA=172.18.11.11
export DATASTORE_VCSA=Temp
export PORTGROUP_VCSA="VM Network"
