#!/bin/bash
#bdereims@vmware.com

#######################

export CPOD=DEVOPS
export SUBNET=172.18.2

#######################

CPOD_LOWER=$( echo ${CPOD} | tr '[:upper:]' '[:lower:]' )
CPOD_HIGH=$( echo ${CPOD} | tr '[:lower:]' '[:upper:]' )
export SITE="cPod-${CPOD_HIGH}"
export DOMAIN=cpod-${CPOD_LOWER}.shwrfr.mooo.com
export DNS=${SUBNET}.1
export NTP=${DNS}
export GATEWAY=${DNS}
export NETMASK=255.255.255.0
export PASSWORD=VMware1!
export VC_PASSWORD=${PASSWORD}
export PORTGROUP="VM Network"
#export ADMIN=administrator%40vsphere.local
export ADMIN=administrator%40${DOMAIN}
export TARGET=vcsa.${DOMAIN}/cPod-${CPOD}/host/Management
export DATASTORE=Datastore
export BITS=/data/BITS

export HOSTNAME_VCSA=vcsa.${DOMAIN}
export HOSTNAME_PSC=psc.${DOMAIN}
export NAME_VCSA=VCSA
export NAME_PSC=PSC
export IP_VCSA=${SUBNET}.9
export IP_PSC=${SUBNET}.10
export OVA_VCSA=${BITS}/VMware-VCSA-all-6.5.0-5973321.iso
export TARGET_VCSA=${SUBNET}.11
export DATASTORE_VCSA=Datastore
export PORTGROUP_VCSA="VM Network"

export HOSTNAME_NSX=nsx.${DOMAIN}
export NAME_NSX=NSX
export IP_NSX=${SUBNET}.21
export OVA_NSX=${BITS}/VMware-NSX-Manager-6.3.3-6276725.ova

export HOSTNAME_PHOTONOS=photonos
export NAME_PHOTONOS=photonos
export OVA_PHOTONOS=${BITS}/photon-hw13-2.0.ova

export HOSTNAME_VIC=VIC
export NAME_VIC=VIC
export IP_VIC=${SUBNET}.30
export OVA_VIC=${BITS}/vic-v1.2.1-4104e5f9.ova
