#!/bin/bash
#bdereims@vmware.com

export DNS=172.18.16.1
export NTP=${DNS}
export DOMAIN=cpod-nsx-pan.shwrfr.mooo.com
export GATEWAY=172.18.16.1
export NETMASK=255.255.255.0
export PASSWORD=VMware1!
export VC_PASSWORD=${PASSWORD}
export PORTGROUP="DPortGroup"
export ADMIN=administrator%40vsphere.local
export TARGET=vcsa.cpod-nsx-pan.shwrfr.mooo.com/Datacenter/host/Mgmt
export DATASTORE=Datastore
export BITS=/data/BITS

export HOSTNAME_VCSA=vcsa.${DOMAIN}
export NAME_VCSA=VCSA
export IP_VCSA=172.18.16.20
export OVA_VCSA=${BITS}/VMware-VCSA-all-6.5.0-5318154.iso
export TARGET_VCSA=172.18.16.219
export DATASTORE_VCSA=Datastore
export PORTGROUP_VCSA="VM Network"

export HOSTNAME_NSX=nsx.cpod-nsx-pan.shwrfr.mooo.com
export NAME_NSX=NSX
export IP_NSX=172.18.16.21
export OVA_NSX=${BITS}/VMware-NSX-Manager-6.3.2-5672532.ova
