#!/bin/bash
#bdereims@vmware.com

export DNS=172.18.1.1
export NTP=${DNS}
export DOMAIN=cpod-vic.shwrfr.mooo.com
export GATEWAY=172.18.1.1
export NETMASK=255.255.255.0
export PASSWORD=VMware1!
export VC_PASSWORD=${PASSWORD}
export PORTGROUP="DPortGroup"
export ADMIN=administrator%40vsphere.local
export TARGET=vcsa.cpod-vic.shwrfr.mooo.com/cPod-VIC/host/Cluster/
export DATASTORE=Datastore
export BITS=/data/BITS

export HOSTNAME_VCSA=vcsa.cpod-vic.shwrfr.mooo.com
export NAME_VCSA=VCSA
export IP_VCSA=172.18.1.20
export OVA_VCSA=${BITS}/VMware-VCSA-all-6.5.0-5318154.iso
export TARGET_VCSA=172.18.1.11
export DATASTORE_VCSA=Temp

export HOSTNAME_VRA=vra.cpod-vic.shwrfr.mooo.com
export NAME_VRA=vRA
export IP_VRA=172.18.1.30
export OVA_VRA=${BITS}/VMware-vR-Appliance-7.3.0.536-5610496_OVF10.ova
