#!/bin/bash
#bdereims@gmail.com

export DNS=192.168.1.2
export NTP=${DNS}
export DOMAIN=cpod.net
export GATEWAY=${DNS}
export NETMASK=255.255.255.0
export PASSWORD=VMware1!
export VC_PASSWORD=${PASSWORD}
export PORTGROUP=DPortGroup
export ADMIN=administrator%40cpod.net
export TARGET=vcenter.cpod.net/Datacenter/host/Admin/esx03.cpod.net/
export DATASTORE=vioDatastore
export BITS=../BITS
