#!/bin/bash
#bdereims@vmware.com

export DNS=10.66.0.15
export NTP=${DNS}
export DOMAIN=cpod.showroom.local
export GATEWAY=10.66.0.1
export NETMASK=255.255.255.0
export PASSWORD=VMware1!
export VC_PASSWORD=${PASSWORD}
export PORTGROUP="VM Network"
export ADMIN=root
export TARGET=10.66.0.11
export DATASTORE=datastore1
export BITS=/data/BITS
export PCONTROLLER=10.66.0.18
export INSTALLVM=10.66.0.17
